#!/bin/bash
myHome=$1

downloads=$myHome/Downloads
downloadsImageFolder=$downloads/Images
downloadsPDFFolder=$downloads/Pdfs
downloadsZipFolder=$downloads/Zips
downloadsDocsFolder=$downloads/Documents
downloadsConfigFolder=$downloads/Configs

desktop=$myHome/Desktop
moveFolder=$desktop/Misc

desktopScreenshotFolder=$moveFolder/Images
desktopPDFFolder=$moveFolder/SomePDFs
desktopDocsFolder=$moveFolder/Documents
desktopZipFolder=$moveFolder/Zips
desktopConfigFolder=$moveFolder/Configs

cleaning(){
    moveImages $1 "$2/Images"
    movePDFs $1 "$2/Pdfs"
    moveMSDocs $1 "$2/Docs"
    moveZIPs $1 "$2/Zips"
    moveConfigs $1 "$2/Configs"
    moveVideos $1 "$2/Videos"
    moveAudio $1 "$2/Videos"
    removeCalendarInvites $1
    removeHTMLDownloads $1
    removeExecutables $1
    removeInstallers $1
}

cleanDesktop(){
    echo "Organizing desktop folder.."
    cleaning $desktop $desktop/Misc
}

cleanDownloads(){
    echo "Organizing downloads folder.."
    cleaning $downloads $downloads   
}

removeCalendarInvites(){
    rm -rf $1/*.ics   
}

removeInstallers(){
    rm -rf $1/*.msi   
    rm -rf $1/*.dmg
}

removeHTMLDownloads(){
    rm -rf $1/*.html   
}

removeExecutables(){
    rm -rf $1/*.exe   
}

moveTo(){
    mkdir -p $2 
    mv $1 $2 2>/dev/null
}
moveAudio(){
    from=$1
    to=$2
    moveTo "$from/*.mp3" "$to" 
    moveTo "$from/*.MP3" "$to" 
    moveTo "$from/*.wav" "$to" 
    moveTo "$from/*.WAV" "$to" 
    
}

moveImages(){
    from=$1
    to=$2
    moveTo "$from/*.jpg" "$to" 
    moveTo "$from/*.Jpg" "$to" 
    moveTo "$from/*.jpeg" "$to" 
    moveTo "$from/*.JPEG" "$to" 
    moveTo "$from/*.JPG" "$to" 
    moveTo "$from/*.png" "$to" 
    moveTo "$from/*.PNG" "$to"
    moveTo "$from/*.heic" "$to" 
    moveTo "$from/*.HEIC" "$to"
}

movePDFs(){
    from=$1
    to=$2
    moveTo "$from/*pdf" "$to"
    moveTo "$from/*PDF" "$to"
}

moveConfigs(){
    from=$1
    to=$2
    moveTo "$from/*xml" "$to"
    moveTo "$from/*json" "$to"
    moveTo "$from/*yaml" "$to"
    moveTo "$from/*yml" "$to"
    moveTo "$from/*.properties" "$to"
}

moveVideos(){
    from=$1
    to=$2
    moveTo "$from/*MOV" "$to"
    moveTo "$from/*mov" "$to"
    moveTo "$from/*mp4" "$to"
    moveTo "$from/*MP4" "$to"
}
moveMSDocs(){
    from=$1
    to=$2
    moveTo "$from/*docx" "$to"
    moveTo "$from/*txt" "$to"
    moveTo "$from/*csv" "$to"
    moveTo "$from/*xlsx" "$to"    
    moveTo "$from/*doc" "$to"
    moveTo "$from/*pptx" "$to"
}

moveZIPs(){
    from=$1
    to=$2
    moveTo "$from/*zip" "$to"
    moveTo "$from/*ZIP" "$to"
}

main(){
    echo "Cleaning in progress..."
    cleanDesktop
    cleanDownloads
    # cleaning 
    echo "Cleaning done!"
}

main