#!/bin/bash
myHome=$1

downloads=$myHome/Downloads
downloadsImageFolder=$downloads/Images
downloadsPDFFolder=$downloads/Pdfs
downloadsZipFolder=$downloads/Zips
downloadsDocsFolder=$downloads/Documents
downloadsConfigFolder=$downloads/Configs

desktop=$myHome/Desktop
moveFolder=$desktop/Misc

desktopScreenshotFolder=$moveFolder/Images
desktopPDFFolder=$moveFolder/SomePDFs
desktopDocsFolder=$moveFolder/Documents
desktopZipFolder=$moveFolder/Zips
desktopConfigFolder=$moveFolder/Configs

cleanDesktop(){
    echo "Organizing desktop folder.."
    moveImages $desktop $desktopScreenshotFolder
    movePDFs $desktop $desktopPDFFolder
    moveMSDocs $desktop $desktopDocsFolder
    moveZIPs $desktop $downloadsZipFolder
    moveConfigs $desktop $desktopConfigFolder
    removeCalendarInvites $desktop
    removeHTMLDownloads $desktop
    removeExecutables $desktop
}

cleanDownloads(){
    echo "Organizing downloads folder.."
    moveImages $downloads $downloadsImageFolder
    movePDFs $downloads $downloadsPDFFolder
    moveZIPs $downloads $downloadsZipFolder
    moveMSDocs $downloads $downloadsDocsFolder
    moveConfigs $downloads $downloadsConfigFolder
    removeCalendarInvites $downloads
    removeHTMLDownloads $downloads
    removeExecutables $downloads
}

removeCalendarInvites(){
    rm -rf $1/*.ics   
}

removeHTMLDownloads(){
    rm -rf $1/*.html   
}

removeExecutables(){
    rm -rf $1/*.exe   
}

moveTo(){
    mkdir -p $2 
    mv $1 $2 2>/dev/null
}

moveImages(){
    from=$1
    to=$2
    moveTo "$from/*.jpg" "$to" 
    moveTo "$from/*.Jpg" "$to" 
    moveTo "$from/*.jpeg" "$to" 
    moveTo "$from/*.JPEG" "$to" 
    moveTo "$from/*.JPG" "$to" 
    moveTo "$from/*.png" "$to" 
    moveTo "$from/*.PNG" "$to"
}

movePDFs(){
    from=$1
    to=$2
    moveTo "$from/*pdf" "$to"
    moveTo "$from/*PDF" "$to"
}

moveConfigs(){
    from=$1
    to=$2
    moveTo "$from/*xml" "$to"
    moveTo "$from/*json" "$to"
    moveTo "$from/*yaml" "$to"
    moveTo "$from/*yml" "$to"
    moveTo "$from/*.properties" "$to"
}
moveMSDocs(){
    from=$1
    to=$2
    moveTo "$from/*docx" "$to"
    moveTo "$from/*txt" "$to"
    moveTo "$from/*csv" "$to"
    moveTo "$from/*xlsx" "$to"    
    moveTo "$from/*doc" "$to"
    moveTo "$from/*pptx" "$to"
}

moveZIPs(){
    from=$1
    to=$2
    moveTo "$from/*zip" "$to"
    moveTo "$from/*ZIP" "$to"
}

main(){
    echo "Cleaning in progress..."
    cleanDesktop
    cleanDownloads
    echo "Cleaning done!"
}

main