#!/bin/bash

myHome=/mnt/c/Users/bhatvive

downloads=$myHome/Downloads
downloadsImageFolder=$downloads/images
downloadsPDFFolder=$downloads/pdfs

desktop=$myHome/Desktop
moveFolder=$myHome/Desktop/Vivek

desktopScreenshotFolder=$moveFolder/Screenshots
desktopPDFFolder=$moveFolder/SomePDFs

# Black        0;30     Dark Gray     1;30
# Red          0;31     Light Red     1;31
# Green        0;32     Light Green   1;32
# Brown/Orange 0;33     Yellow        1;33
# Blue         0;34     Light Blue    1;34
# Purple       0;35     Light Purple  1;35
# Cyan         0;36     Light Cyan    1;36
# Light Gray   0;37     White         1;37

RED='\033[0;31m'
NC='\033[0m' # No Color
printf "By ${RED}Vivek Bhat ${NC}\n"

cleanDesktop(){
    moveImages $desktop $desktopScreenshotFolder
    movePDFs $desktop $desktopPDFFolder
    echo "Cleaned your desktop :)"
}

cleanDownloads(){
    moveImages $downloads $downloadsImageFolder
    movePDFs $downloads $downloadsPDFFolder
    echo "Cleaned your Downloads Folder :)"
}

moveTo(){
    mv $1 $2 2>/dev/null
}

moveImages(){
    from=$1
    to=$2
    moveTo "$from/*.jpg" "$to" 
    moveTo "$from/*.Jpg" "$to" 
    moveTo "$from/*.JPG" "$to" 
    moveTo "$from/*.png" "$to" 
    moveTo "$from/*.PNG" "$to"
}

movePDFs(){
    from=$1
    to=$2
    moveTo "$from/*pdf" "$to"
    moveTo "$from/*PDF" "$to"
}

main(){
    cleanDesktop
    cleanDownloads
}

main