#!/bin/bash

# Function to add profile line if it doesn't exist
add_profile_line() {
    local profile_file="$1"
    local profile_name="$2"

    if grep -q "\bsource \$HOME/Projects/bash_scripts/Debian/$profile_name\b" "$profile_file"; then
        echo "$profile_name Profile exists in $profile_file"
    else
        echo "source \$HOME/Projects/bash_scripts/Debian/$profile_name" >>"$profile_file"
        echo "Added $profile_name in $profile_file successfully"
    fi
}

# Add ZSH Profile line
add_profile_line ~/.zshrc zsh_profile

# Add Bash Profile line
add_profile_line ~/.bashrc bash_profile
