#!/bin/bash
#####################################################
# First run the Unix/installer.sh to install in WSL #
#####################################################
SCRIPT_DIR=$(dirname "$0")
COMPUTERS_DIR=$(dirname "$SCRIPT_DIR")
UNIX_DIR=$(dirname "$COMPUTERS_DIR")
ALL_SCRIPTS_FOLDER=$(dirname "$UNIX_DIR")

COMMON_SCRIPTS_FOLDER=$UNIX_DIR/common_scripts

PROJECTS_FOLDER="$HOME/Projects"

source $COMMON_SCRIPTS_FOLDER/bash_lib/common.sh
source $COMMON_SCRIPTS_FOLDER/bash_lib/git_helpers.sh
source $COMMON_SCRIPTS_FOLDER/bash_lib/personal_helpers.sh
source $COMMON_SCRIPTS_FOLDER/work/hughes.sh
source $COMMON_SCRIPTS_FOLDER/work/aws_helpers.sh
source $COMMON_SCRIPTS_FOLDER/work/backup_owaiops.sh

# Run the cleanup script every time terminal is launched
$UNIX_DIR/cleanup/cleanup.sh
