#!/bin/bash
# Run the Unix/installer.sh to install in WSL
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
COMPUTERS_DIR=$(dirname "$SCRIPT_DIR")
UNIX_DIR=$(dirname "$COMPUTERS_DIR")

PROJECTS_FOLDER="$HOME/Projects"

COMMON_SCRIPTS_FOLDER=$UNIX_DIR/common_scripts

export VIRTUAL_ENV_DISABLE_PROMPT=true

source $COMMON_SCRIPTS_FOLDER/bash_lib/common.sh
source $COMMON_SCRIPTS_FOLDER/bash_lib/git_helpers.sh
source $COMMON_SCRIPTS_FOLDER/bash_lib/wsl_helpers.sh
source $COMMON_SCRIPTS_FOLDER/work/hughes.sh
source $COMMON_SCRIPTS_FOLDER/work/aws_helpers.sh
source $COMMON_SCRIPTS_FOLDER/work/backup_owaiops.sh

export BROWSER=wslview
