#!/bin/bash
# Run the Unix/installer.sh to install in WSL
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
COMPUTERS_DIR=$(dirname "$SCRIPT_DIR")
UNIX_DIR=$(dirname "$COMPUTERS_DIR")

# Needed for prof method that opens this bash project
ALL_SCRIPTS_FOLDER=$(dirname "$UNIX_DIR")

COMMON_SCRIPTS_FOLDER=$UNIX_DIR/common_scripts

source $COMMON_SCRIPTS_FOLDER/bash_lib/common.sh
source $COMMON_SCRIPTS_FOLDER/bash_lib/git_helpers.sh
source $COMMON_SCRIPTS_FOLDER/bash_lib/wsl_helpers.sh
source $COMMON_SCRIPTS_FOLDER/work/hughes.sh
source $COMMON_SCRIPTS_FOLDER/work/aws_helpers.sh
source $COMMON_SCRIPTS_FOLDER/work/backup_owaiops.sh

# Cleanup
# $UNIX_DIR/cleanup/wsl_cleanup.sh "/mnt/c/Users/vbhat01/OneDrive - Echostar Operating L.L.C"
