#!/bin/bash
# Run the Unix/installer.sh to install in WSL
export PROJECTS_FOLDER="$HOME/Projects"
export PVT_REPO_DIR="$PROJECTS_FOLDER/private"
export BASH_SCRIPTS="$PVT_REPO_DIR/bash_scripts"
export UNIX_SCRIPT_DIR="$BASH_SCRIPTS/Unix"
export COMMON_SCRIPTS_FOLDER="$UNIX_SCRIPT_DIR/common_scripts"

source $COMMON_SCRIPTS_FOLDER/bash_lib/common.sh
source $COMMON_SCRIPTS_FOLDER/bash_lib/git_helpers.sh
source $COMMON_SCRIPTS_FOLDER/bash_lib/wsl_helpers.sh
source $COMMON_SCRIPTS_FOLDER/work/hughes.sh
source $COMMON_SCRIPTS_FOLDER/work/aws_helpers.sh
source $COMMON_SCRIPTS_FOLDER/work/backup_owaiops.sh

# Cleanup
# $UNIX_DIR/cleanup/wsl_cleanup.sh "/mnt/c/Users/vbhat01/OneDrive - Echostar Operating L.L.C"
