#!/bin/bash
WSL_SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
OS_FOLDER=$(dirname "$WSL_SCRIPT_DIR")
BASH_SCRIPTS_FOLDER=$(dirname "$OS_FOLDER")
PROJECTS_FOLDER="$HOME/Projects"

LINUX_SCRIPTS_FOLDER=$OS_FOLDER/Linux

source $LINUX_SCRIPTS_FOLDER/bash_lib/common.sh
source $LINUX_SCRIPTS_FOLDER/bash_lib/git_helpers.sh
source $LINUX_SCRIPTS_FOLDER/work/hughes.sh
source $LINUX_SCRIPTS_FOLDER/work/aws_helpers.sh
source $LINUX_SCRIPTS_FOLDER/work/backup_owaiops.sh
